name: Build and publish Docker images (alpine)

on:
  push:
    branches:
      - 'release/**'
    tags:
      - 'v*'

jobs:
  build-and-publish-images:
    name: Build alpine image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and publish image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./alpine/Dockerfile
          push: true
          tags: humenius/traefik-certs-dumper:alpine-test
  
      - name: Build and publish image (arm32v7)
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./alpine/Dockerfile.armhf
          platforms: linux/arm/v7
          push: true
          tags: humenius/traefik-certs-dumper:alpine-arm32v7-test

      - name: Build and publish image (arm64v8)
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./alpine/Dockerfile.aarch64
          platforms: linux/arm64/v8
          push: true
          tags: humenius/traefik-certs-dumper:alpine-arm64v8-test
