name: Build and publish Docker images (alpine)

on:
  push:
    branches:
      - 'release/**'
    tags:
      - 'v*'

env:
  DOCKER_IMAGE: humenius/traefik-certs-dumper

jobs:
  build-and-publish-images:
    name: Build alpine image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Prepare tags
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ${{ env.DOCKER_IMAGE }}
          tag-semver: |
            {{version}}-alpine
            {{major}}.{{minor}}-alpine
            {{major}}-alpine
          tag-custom: |
            alpine
          tag-latest: false

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to Docker Hub registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and publish image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./alpine/Dockerfile
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          # push: ${{ github.event_name != 'pull_request' }}
          push: false
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
  
      - name: Build and publish image (arm32v7)
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./alpine/Dockerfile.armhf
          platforms: linux/arm/v7
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          # push: ${{ github.event_name != 'pull_request' }}
          push: false
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}

      - name: Build and publish image (arm64v8)
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./alpine/Dockerfile.aarch64
          platforms: linux/arm64/v8
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          # push: ${{ github.event_name != 'pull_request' }}
          push: false
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
